services:
  caddy:
    # Using regular Caddy (not docker-proxy) for simpler ACME handling
    image: caddy:2.9-alpine
    container_name: caddy_nodo0
    restart: always

    env_file:
      - ../.env

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3 support
      # Optional: Caddy admin API (only on localhost for security)
      # - "127.0.0.1:2019:2019"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro           # Main config
      - ./data:/data                                   # Persistent ACME certificates
      - ./config:/config                               # Caddy internal config
      - ../logs:/var/log/caddy                         # Logs directory

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/config/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

    # Logging driver
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        labels: "production"
        tag: "caddy-nodo0"

    networks:
      - edge

networks:
  edge:
    external: true
    name: ${CADDY_DOCKER_NETWORK:-internal-nodo0-web}
