version: "3.9"

networks:
  edge:
    external: true
    name: ${CADDY_DOCKER_NETWORK:-internal-nodo0-web}

services:
  example-app:
    image: traefik/whoami:v1.10
    container_name: example_app_nodo0
    restart: always
    networks:
      - edge

    # Caddy Docker Proxy labels for automatic discovery
    labels:
      # Enable Caddy auto-discovery with hostname
      caddy: "example.infra.cluster.qb.fcen.uba.ar"

      # Reverse proxy to port 80 (whoami default)
      caddy.reverse_proxy: "{{upstreams 80}}"

      # Automatic HTTPS with Let's Encrypt
      # (omit caddy.tls or set to empty for automatic)

      # Optional: Add custom response headers
      caddy.header.X-Served-By: "Caddy-nodo0"
