version: "3.9"

networks:
  edge:
    external: true
    name: ${TRAEFIK_DOCKER_NETWORK}

services:
  example-app:
    image: traefik/whoami:v1.10
    container_name: example_app_nodo0
    restart: always
    networks:
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_DOCKER_NETWORK}"

      - "traefik.http.routers.example.rule=Host(`example.infra.cluster.qb.fcen.uba.ar`)"
      - "traefik.http.routers.example.entrypoints=websecure"
      - "traefik.http.routers.example.tls=true"
      - "traefik.http.routers.example.tls.certresolver=leresolver"
      - "traefik.http.services.example.loadbalancer.server.port=80"

      - "traefik.http.routers.example-http.rule=Host(`example.infra.cluster.qb.fcen.uba.ar`)"
      - "traefik.http.routers.example-http.entrypoints=web"
      - "traefik.http.routers.example-http.middlewares=https_redirect@file"
