version: "3.9"

networks:
  edge:
    external: true
    name: ${TRAEFIK_DOCKER_NETWORK}

services:
  genphenia-api:
    container_name: genphenia_api_nodo0
    build: .
    image: genphenia-api:latest
    restart: always
    networks:
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_DOCKER_NETWORK}"
      - "traefik.routing.enable=true"

      - "traefik.http.routers.genphenia-api.rule=Host(`genphenia.infra.cluster.qb.fcen.uba.ar`)"
      - "traefik.http.routers.genphenia-api.entrypoints=websecure"
      - "traefik.http.routers.genphenia-api.tls=true"
      - "traefik.http.routers.genphenia-api.tls.certresolver=leresolver"
      - "traefik.http.services.genphenia-api.loadbalancer.server.port=8080"

      - "traefik.http.routers.genphenia-api-http.rule=Host(`genphenia.infra.cluster.qb.fcen.uba.ar`)"
      - "traefik.http.routers.genphenia-api-http.entrypoints=web"
      - "traefik.http.routers.genphenia-api-http.middlewares=https_redirect@file"

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
