# --- SOLO el bypass de ACME, para emitir el cert ---
[http.routers]
  [http.routers.acme-http01]
    rule = 'PathPrefix(`/.well-known/acme-challenge/`)'
    entryPoints = ["web"]
    service = "noop@internal"
    priority = 100000
