[http.middlewares]
  [http.middlewares.https_redirect.redirectscheme]
    scheme = "https"
    permanent = true

[http.routers]
  [http.routers.traefik-dashboard]
    rule = "Host(`{{ env "TRAEFIK_DASHBOARD_HOST" }}`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    [http.routers.traefik-dashboard.tls]
      certResolver = "leresolver"

  [http.routers.traefik-dashboard-http]
    rule = "Host(`{{ env "TRAEFIK_DASHBOARD_HOST" }}`)"
    entryPoints = ["web"]
    service = "api@internal"
    middlewares = ["https_redirect"]
