[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    network = "{{ env 'TRAEFIK_DOCKER_NETWORK' }}"
  [providers.file]
    filename = "/etc/traefik/dynamic/dynamic.toml"
    watch = true

[api]
  dashboard = true
  insecure = false

[certificatesResolvers]
  [certificatesResolvers.leresolver]
    [certificatesResolvers.leresolver.acme]
      email = "{{ env 'LE_EMAIL'}}"
      storage = "/acme.json"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      [certificatesResolvers.leresolver.acme.httpChallenge]
        entryPoint = "web"
