[entryPoints]
  [entryPoints.web]
    address = ":80"
    # SIN redirección global aquí (comentado)
    # [entryPoints.web.http.redirections.entryPoint]
    #   to = "websecure"
    #   scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]

# [providers]
#   [providers.docker]
#     exposedByDefault = false
#     watch = false
  [providers.file]
    filename = "/etc/traefik/dynamic/dynamic.toml"
    watch = true

[certificatesResolvers.leresolver.acme]
  email = "mateo@lucai.bio"
  storage = "/acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.leresolver.acme.httpChallenge]
    entryPoint = "web"
# (sin tlsChallenge aquí)
