[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    watch = true
    # IMPORTANTE: no pongas "network = {{ env ... }}" aquí; si querés, quitalo.
  [providers.file]
    filename = "/etc/traefik/dynamic/dynamic.toml"
    watch = true

[api]
  dashboard = true
  insecure = true   # ← TEMPORAL para debug; luego lo volvemos a false

[certificatesResolvers.leresolver.acme]
  email = "mateo@lucai.bio"        # o el que uses
  storage = "/acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.leresolver.acme.httpChallenge]
    entryPoint = "web"


# Router estático para que HTTP-01 no sea redirigido a HTTPS:
[http.routers]
  [http.routers.acme-http01]
    rule = "PathPrefix(`/.well-known/acme-challenge/`)"
    entryPoints = ["web"]
    service = "noop@internal"