[http.middlewares]
  [http.middlewares.https_redirect.redirectscheme]
    scheme = "https"
    permanent = true

[http.routers]
  [http.routers.traefik-dashboard]
    rule = "Host(`traefik.infra.cluster.qb.fcen.uba.ar`)"
    entryPoints = ["websecure"]
    service = "api@internal"
    [http.routers.traefik-dashboard.tls]
      certResolver = "leresolver"

  [http.routers.traefik-dashboard-http]
    rule = "Host(`traefik.infra.cluster.qb.fcen.uba.ar`)"
    entryPoints = ["web"]
    service = "api@internal"
    middlewares = ["https_redirect"]
